services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: analisis-numerico-backend
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - analisis-numerico-network
    volumes:
      - ./backend:/app
    command: uvicorn app:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: analisis-numerico-frontend
    ports:
      - "3000:3000"
    networks:
      - analisis-numerico-network
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://localhost:8000

networks:
  analisis-numerico-network:
    driver: bridge
